POST http://127.0.0.1:26382/index
content-type: application/json

{
    "name": "eqp_simulator",
    "lot_type": 0,
    "log": "[2025-09-12 09:24:32.606 +08:00] [INF] [Nucleus] SECS/GEM EAP: --> [0x000007C9] 'S1F14'\n    <L [2] \n        <B [0] >\n        <L [2] \n            <A [6] '8800FC'>\n            <A [5] '1.0.0'>\n        >\n    >\n.\n",
    "tags": [
        {
            "label": "secs",
            "value": "S1F14"
        }
    ]
}

###

POST http://127.0.0.1:26382/index/mapping
content-type: application/json

{
    "name": "eqp_simulator",
    "log_type": "raw",
    "log_header": "eqp",
    "log_regex": "\\[(?P<time>[^\\]]*)\\] \\[(?P<level>[^\\]]*)\\] \\[(?P<name>[^\\]]*)\\] (?P<msg>.*)$",
    "fields": [
        {
            "name": "time",
            "type": "string"
        },
        {
            "name": "level",
            "tag_name": "level",
            "type": "string"
        },
        {
            "name": "name",
            "tag_name": "name",
            "type": "string"
        },
        {
            "name": "secs",
            "tag_name": "secs",
            "type": "string"
        },
        {
            "name": "msg",
            "type": "string"
        }
    ]
}

###

http://127.0.0.1:26382/index/mappings

###

http://127.0.0.1:26382/search?name=eap&log_type=raw